### ISSUE TITLE
reverse axis

### ISSUE THREAD

**Issue by hwchen** [SiegeLord/RustGnuplot#16]
Hi! Thanks for your work on this, it's been really helpful for plotting.

I'd like to reverse an axis. As far as I can tell, that is not currently a feature (but maybe I missed it?).

If you'd like, I can make a pull request for it.

**Comment by SiegeLord** [comment]
Doesn't look like it can be done. Feel free to send in a pull request. Without thinking too much, a reasonable API would be to just add another one of `set_x_reverse` or something like that.

**Comment by hwchen** [comment]
Thanks again! closed by #17
