### ISSUE TITLE
Errorbars on points without connecting lines?

### ISSUE THREAD

**Issue by cbourjau** [SiegeLord/RustGnuplot#24]
Thanks for this nice library! I discovered that RustGnuplot uses gnuplot's [errorlines](http://gnuplot.sourceforge.net/docs_4.2/node141.html#errorlines) in order to plot points with error bars. Is there a way to use [errorbar](http://gnuplot.sourceforge.net/docs_4.2/node140.html) instead? If i understand the documentation correctly, one could achieve the former by using `errorbar` + `plot`. On the other hand it seems like one cannot turn off the lines once they are plotted with `errorlines`. I also tried setting the linewidth to 0 to no avail. Am I missing something?

**Comment by SiegeLord** [comment]
Actually, it might take me a little bit of time to push a new version to crates.io, as I'm in a middle of refactoring and need to check that I didn't break anything. I'll try to prioritize this.

**Comment by cbourjau** [comment]
Thanks a lot for this swift response! I will give it a spin later today and report back if there are any issues!
