### ISSUE TITLE
`set y2tics` command is supported?

### ISSUE THREAD

**Issue by knknkn1162** [SiegeLord/RustGnuplot#25]
Hi.

I want to set mutiple y axes in the left side(the first axis) and right size(the 2nd axis).
In the gnuplot document, I found that `set y2tics` is what I need. 
So, does RustGnuplot support `set y2tics` gnuplot command? I couldn't find it in your library😢

**Comment by SiegeLord** [comment]
Not currently supported, but it could be added.
