### ISSUE TITLE
Caption ownership troubles

### ISSUE THREAD

**Issue by dvtomas** [SiegeLord/RustGnuplot#26]
Hi, 
I'm quite new to rust, so I'm still struggling with lifetimes, ownerships et al.

I'd like to do this (stripped down to the essence):

```rust
use gnuplot::Figure;
pub fn make_figure<'a>(x: f64, y: f64) -> Figure<'a> {
    use gnuplot::Caption;
    let point_caption = format!("Point, x = {}, y = {}", x, y);
    let mut fg = Figure::new();
    let axes = fg.axes2d();
    axes.points(&[x], &[y], &[Caption(&point_caption)]);
    fg
}
```

However, `point_caption` is created locally so it is dropped on function return. `axes.points` passes it in Caption via reference, so it requires it to live at least as long as the figure being returned. Thus, given snippet does not compile.

What should I do here? Passing the caption in parameters to `make_figure` would be very annoying, is there a better way available?

**Comment by SiegeLord** [comment]
Hmm, that's very unfortunate. I'll have to think about how to fix this.

**Comment by dvtomas** [comment]
Awesome, thank you!
