### ISSUE TITLE
fg.show() doesn't do anything

### ISSUE THREAD

**Issue by ManifoldFR** [SiegeLord/RustGnuplot#29]
I have the following code:

```rust
// myexample.rs
let mut fg = Figure::new();
    
fg.set_terminal("qt", "");

fg.axes2d()
        .lines(&times, &lambda_values,
            &[
                Caption("λ(t)"),
                Color("#1E90FF"),
            ])
        .points(&event_times, &event_intens, 
            &[
                Caption("Events"),
                Color("black"),
                PointSymbol('O'),
                PointSize(0.8)])
        .set_x_label("Temps t", &[])
        .set_y_label("Intensité", &[]);
    
fg.show();
```

But when I run `cargo run --example myexample`, the gnuplot window doesn't show up (not even for a split second). When I choose a different backend such as pngcairo and an output file, it won't create the file either. I have to echo to a .gnuplot file and run gnuplot manually.

I'm running Windows 10 64-bit, with Rust 1.26.2 and gnuplot 5.3.

**Comment by SiegeLord** [comment]
To be clear, when you say echo you mean `fg.echo_to_file`? If so, then that's very strange, as `fg.show` uses the same output to interact with gnuplot. Does this happen only for this code or everything? Have you tried running one of RustGnuplot's examples (I'm guessing the easiest way is to clone the repository and then do `cargo run --example box_and_whisker`.

**Comment by ManifoldFR** [comment]
Yes, I do `fg.echo_to_file` to get the gnuplot file. Running the example as you said gives me
```commandline
$ cargo run --example box_and_whisker -- --terminal wxt
warning: unused manifest key: package.autobenches
warning: unused manifest key: package.autobins
warning: unused manifest key: package.autoexamples
warning: unused manifest key: package.autotests
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target\debug\examples\box_and_whisker.exe --terminal wxt`
help:Some("false")
no-show:Some("false")
terminal:Some("wxt")
```
but no window shows up. Same with using `qt` and `windows`.

**Comment by ManifoldFR** [comment]
Thanks, that worked. That is quite surprising behaviour!

**Comment by SiegeLord** [comment]
Should be fixed, as the associated cargo bug is fixed.
