### ISSUE TITLE
Date\Time axis support

### ISSUE THREAD

**Issue by snuk182** [SiegeLord/RustGnuplot#30]
Either with std::time or chrono please. The raw unix timestamps work but not handy in axis labeling.

**Comment by plyhun** [comment]
For now it either can be done via `set_x_ticks_custom(ticks, options.as_slice(), labels.as_slice())` with no log axis possibility:
![image](https://user-images.githubusercontent.com/25364263/45943166-8c79ab00-bfe5-11e8-8a74-3ea095c088b8.png)
or via `` with no formatted date output:
![image](https://user-images.githubusercontent.com/25364263/45943221-c64ab180-bfe5-11e8-843f-43e4def4f5ae.png)
Both look ugly :(

**Comment by SiegeLord** [comment]
I am confused, `set_x_ticks_custom` should work fine with log axes, I just verified it that it works.

I have just figured out how to implement this automatically, however, hopefully this will be implemented properly soon.

**Comment by SiegeLord** [comment]
7508a74fb2599accfedffca4fa73a8c27c766d67 adds support for this, as I understand it. See [examples/time.rs](https://github.com/SiegeLord/RustGnuplot/blob/master/examples/time.rs) for an example.
