### ISSUE TITLE
How to create gif animation?

### ISSUE THREAD

**Issue by HarukiUchito** [SiegeLord/RustGnuplot#36]
Hello, I'm trying to create gif animation by the code like following.
But only last frame was recorded in "movie.gif".
Is this the wrong usage of functions or the limitation of the current package?
```
let mut fg = Figure::new();
fg.set_terminal("gif animate optimize delay 2 size 480,360", "movie.gif");
for _ in 0..10 {
    fg.clear_axes();
    // calculate x, y
    fg.axes2d().lines_points(&x,&y);
    fg.show();
}
```

**Comment by SiegeLord** [comment]
Thanks for reporting this, it was not possible to do this before but I added a new function to enable this in version 0.0.30. See the https://github.com/SiegeLord/RustGnuplot/blob/master/examples/gif.rs example for how to do it.

**Comment by HarukiUchito** [comment]
Thank you!
