### ISSUE TITLE
Not alternating colors when drawing lines

### ISSUE THREAD

**Issue by gdesmott** [SiegeLord/RustGnuplot#37]
Not sure if I'm doing anything wrong but with this example both lines are drawn using the same color, making impossible to distinguish them. Using `points()` instead of `lines()` does alternate the color and pattern. Shouldn't `lines()` do it as well?

```rust
use gnuplot::*;

fn main() {
    let mut fg = Figure::new();

    fg.axes2d()
        .lines(&[1, 2, 3], &[1, 2, 3], &[Caption("fst")])
        .lines(&[1, 2, 3], &[4, 5, 6], &[Caption("snd")]);

    fg.show();
}
```

**Comment by SiegeLord** [comment]
Interesting, this has been the behavior from the very beginning, but I'm not sure why it is that way. I think I don't mind making it change automatically. In the mean time, you can always give the lines separate colors manually via the `Color` option.

**Comment by gdesmott** [comment]
Do we have an easy way to iterate over existing easy enough to differentiate colors? I don't really care about the actual colors used, I just want the figure to be readable. It's getting tricky when we don't know beforehand how many data sets will be displayed.

**Comment by SiegeLord** [comment]
I'm going to just default to gnuplot's default handling of this. It'll iterate between 8 colors.
