### ISSUE TITLE
Arguments describing filenames should be `&Path`/`PathBuf`

### ISSUE THREAD

**Issue by PureW** [SiegeLord/RustGnuplot#60]
Arguments describing filenames, for example in the `save_to_*` functions should be of type `&Path`.

See example signature:
```
pub fn set_terminal<'l>(
  &'l mut self, terminal: &str,
  output_file: &Path   // <-- This becomes a Path
) -> &'l mut Figure
```

**Comment by SiegeLord** [comment]
Thanks. I fixed the API, but the underlying functionality of supporting non-UTF8 paths isn't done yet, tracked by  #61.
