### ISSUE TITLE
Escaped strings prevent newlines

### ISSUE THREAD

**Issue by richli** [SiegeLord/RustGnuplot#66]
With 68f89f19f94fd292ac2d6f152a1d1c714a161d5e applied, it's no longer possible to use labels with embedded newlines.

Minimal example:
```rust
use gnuplot::{AxesCommon, Coordinate, Figure};

fn main() {
    let mut fg = Figure::new();
    let _ax = fg
        .axes2d()
        .label(r"multi\nline\nstring", Coordinate::Graph(0.), Coordinate::Graph(0.), &[]);

    let mut stdout = std::io::stdout();
    fg.echo(&mut stdout);
}
```

With `gnuplot` 0.0.34, the output includes:

```
set label 1 "multi\nline\nstring" at  graph 8.0000000000000004e-1, graph 9.0000000000000002e-1 front
```

And with `gnuplot` 0.0.36, the output includes:

```
set label 1 "multi\\nline\\nstring" at  graph 8.0000000000000004e-1, graph 9.0000000000000002e-1 front
```

I'm not sure what would be the best way to handle this. At first I considered that you could add some whitelisted sequences in `util::escape()` to permit `\n` and maybe others. But then that breaks if you use a path of `C:\new plot`, for example.

From the Gnuplot documention, part III, the "cd" command, it suggests using single-quotes for Windows paths. Maybe it would be better in this crate to be able support writing string literals with either double quotes or single quotes.

**Comment by SiegeLord** [comment]
Thanks for the report, this is interesting. Shouldn't the answer be to 1) not use raw strings on Rust's side 2) escape newlines etc? Let me try implementing this idea.
