### ISSUE TITLE
PDF output size in pixels

### ISSUE THREAD

**Issue by KiaShakiba** [SiegeLord/RustGnuplot#78]
Is there any way to set the output PDF size in pixels, not inches. Or at least specify the size in inches, though support fractional sizes?

**Comment by SiegeLord** [comment]
I don't think you can specify it in pixels, but fractional inches should be fine. I've added this. Let me push a new version as well.

**Comment by KiaShakiba** [comment]
Thanks! That's super helpful. Just in case you were looking for a way to do this, I believe other gnuplot libraries (e.g. sciplot for C++) take pixel values for the pdf then convert to inches internally using a DPI of 72.
