### ISSUE TITLE
Lines draws where it shouldn't

### ISSUE THREAD

**Issue by acrilique** [SiegeLord/RustGnuplot#80]
![diode-resistor-DC-sweep](https://github.com/SiegeLord/RustGnuplot/assets/26299932/b18ef979-f7d4-497e-a923-3d1a0e80a28e)
I'm posting this because I don't see a reason why would .lines produce this output when the dataset is clearly only a curve and not 2 curves. 
At the left there's the lines representation and at the right there's the points representation. If this is the expected behavior, I will close the issue and stick to using points.
My code is this: 
`   
    let mut fg: Figure = Figure::new();

    fg.set_multiplot_layout(1, 2);

    fg.axes2d().lines(&vi, &vo, &[Caption("DC Sweep"), Color("blue")]);

    fg.axes2d().points(&vi, &vo, &[Caption("DC Sweep"), Color("black")]);

    fg.show();  `

The dataset (vi and vo) is this: 
[diode-resistor-DC-sweep.txt](https://github.com/SiegeLord/RustGnuplot/files/11642287/diode-resistor-DC-sweep.txt)

**Comment by SiegeLord** [comment]
Your v0 dataset contains a sweep from -1 to 1, but the final point is at `(-1, 0)` which causes the second line. Note this point is also visible in the points plot, if you adjust the range.
