### ISSUE TITLE
multiplot output differences

### ISSUE THREAD

**Issue by alexb7711** [SiegeLord/RustGnuplot#88]
When I run the `multiplot_options.rs` via `cargo run --example muliplot_options`, the only thing drawn is "Parabola 3" (or whatever the last plot drawn was).

![image](https://github.com/alexb7711/sa-pap/assets/42049885/a6f7172a-9e65-4aa7-b186-2dcca2927e40)

When I execute `gnuplot --persist multiplot_options.gnuplot`, it properly draws all three figures.

![image](https://github.com/alexb7711/sa-pap/assets/42049885/5fbf8229-8ee6-4248-a9f5-0dabc28431aa)

**Comment by SiegeLord** [comment]
Please try this again with the latest version (0.0.40).

**Comment by alexb7711** [comment]
That seemed to do the trick. Appreciate the help!
