### ISSUE TITLE
gnuplot 6.0 has graph disipearing if i move it on 3d graphs

### ISSUE THREAD

**Issue by bgkillas** [SiegeLord/RustGnuplot#89]
on 3d graphs(in my case just points with no lines) when i graph the data it shows, but disipears when i move it(just a blank canvas appears, with no legend in top right also). it also disipears if i make the window small or large this time with the error 'line 0: load/eval nested too deeply' outputted. cant seemingly replicate either in normal gnuplot

**Comment by bgkillas** [comment]
this example
``use gnuplot::{Caption, Figure};
fn main() {
        let mut fg = Figure::new();
                            fg.axes3d()
                            .lines_points(
                                -1000..1000,
                                -1000..1000,
                                -1000..1000,
                                &[
                                    Caption("test"),
                                ],
                            )
        ;    fg.show();
loop{}
}``
gives the error


gnuplot> splot "-" binary endian=little record=2000 format="%float64" using 1:2:3 with linespoints lw 1 t "test"
                                                                                                                ^
         "$GPVAL_LAST_MULTIPLOT" line 66: All points x value undefined

also the 3d examples in 'examples' fail similarly with 6.0

**Comment by SiegeLord** [comment]
I believe this is a bug in gnuplot... but perhaps RustGnuplot should be using a different way to send data to gnuplot that is a bit less fragile.

**Comment by SiegeLord** [comment]
Filed a gnuplot bug report: https://sourceforge.net/p/gnuplot/bugs/2679/

**Comment by bgkillas** [comment]
maybe, also happens irregularly in 2d plots but never made it consistent, still to do with moving the plot

**Comment by SiegeLord** [comment]
0.0.40 switches to using temporary files for passing data to gnuplot, so this is worked around. I wish gnuplot provided a sane way to inline binary data... but it does not.
