### ISSUE TITLE
in gnuplot 6.0 with 0.0.40 i cant pan/zoom in 2d graphs

### ISSUE THREAD

**Issue by bgkillas** [SiegeLord/RustGnuplot#90]
dont have time to test much, but sure didn't happen in 0.0.39 or in gnuplot cli, and reverting to gnuplot 5 fixes it

**Comment by SiegeLord** [comment]
gnuplot seems to have broke something. This sometimes even causes it to crash: https://sourceforge.net/p/gnuplot/bugs/2680/

**Comment by SiegeLord** [comment]
In general, it appears gnuplot changed how multiplot works with the interactive terminals. Perhaps I can disable multiplot for single-axis figures.

**Comment by SiegeLord** [comment]
0.0.41 disables multiplot when plotting just a single axis, so... this usually shouldn't happen.
