### ISSUE TITLE
Real time rendering

### ISSUE THREAD

**Issue by SalahEddineGhamri** [SiegeLord/RustGnuplot#93]
Any ideas how to add live plotting? gnuplot is capable of such realtime data feed using some ".dat" file or direct "replot" 
Currently, calling "fg.show()" will just gnuplot and no return to main is happening.

**Comment by SiegeLord** [comment]
Have you tried the pattern in https://github.com/SiegeLord/RustGnuplot/blob/master/gnuplot/examples/animation_example.rs, is that what you want?

**Comment by SalahEddineGhamri** [comment]
I have tried it. Works fine for me I will adopt the tool.
