### ISSUE TITLE
set_palette caused error

### ISSUE THREAD

**Issue by bgkillas** [SiegeLord/RustGnuplot#99]
been trying to get domain coloring and noticed that 
```.set_palette(PaletteType::Custom(&[(1.0, 1.0, 1.0, 1.0)]))```
fails with
```
gnuplot> set palette defined (1.000000000000e0 1.000000000000e0 1.000000000000e0 1.000000000000e0)
                                                                                                 ^
         line 0: invalid palette syntax
```

**Comment by SiegeLord** [comment]
Thanks for reporting! You need at least two palette entries. The documentation/internal correctness check was wrong.
